[information]
name       = "base16"
background = "dark"
author     = "Bram de Haan (http://atelierbramdehaan.nl)"
slug       = "base16-atelier-dune"

[palette]
base00 = "#20201d"
base01 = "#292824"
base02 = "#6e6b5e"
base03 = "#7d7a68"
base04 = "#999580"
base05 = "#a6a28c"
base06 = "#e8e4cf"
base07 = "#fefbec"
base08 = "#d73737"
base09 = "#b65611"
base0A = "#ae9513"
base0B = "#60ac39"
base0C = "#1fad83"
base0D = "#6684e1"
base0E = "#b854d4"
base0F = "#d43552"

[global]
base16_gui00 = "20201d"
base16_gui01 = "292824"
base16_gui02 = "6e6b5e"
base16_gui03 = "7d7a68"
base16_gui04 = "999580"
base16_gui05 = "a6a28c"
base16_gui06 = "e8e4cf"
base16_gui07 = "fefbec"
base16_gui08 = "d73737"
base16_gui09 = "b65611"
base16_gui0A = "ae9513"
base16_gui0B = "60ac39"
base16_gui0C = "1fad83"
base16_gui0D = "6684e1"
base16_gui0E = "b854d4"
base16_gui0F = "d43552"

base16_cterm0E = "05"
base16_cterm00 = "00"
base16_cterm03 = "08"
base16_cterm05 = "07"
base16_cterm07 = "15"
base16_cterm08 = "01"
base16_cterm0A = "03"
base16_cterm0B = "02"
base16_cterm0C = "06"
base16_cterm0D = "04"

base16_cterm01 = "10"
base16_cterm02 = "11"
base16_cterm04 = "12"
base16_cterm06 = "13"
base16_cterm09 = "09"
base16_cterm0F = "14"

terminal_color_0          = "#20201d"
terminal_color_1          = "#d73737"
terminal_color_2          = "#60ac39"
terminal_color_3          = "#ae9513"
terminal_color_4          = "#6684e1"
terminal_color_5          = "#b854d4"
terminal_color_6          = "#1fad83"
terminal_color_7          = "#a6a28c"
terminal_color_8          = "#7d7a68"
terminal_color_9          = "#d73737"
terminal_color_10         = "#60ac39"
terminal_color_11         = "#ae9513"
terminal_color_12         = "#6684e1"
terminal_color_13         = "#b854d4"
terminal_color_14         = "#1fad83"
terminal_color_15         = "#fefbec"
terminal_color_background = "#20201d"
terminal_color_foreground = "#b854d4"

["Vim editor colors"]
Normal       = "base05 base00"
NormalFloat  = "_ base16"
FloatBorder  = ""
Bold         = "- - b"
Debug        = "base08"
Directory    = "base0D"
Error        = "base00 base08"
ErrorMsg     = "base08 base00"
Exception    = "base08"
FoldColumn   = "base0C base01"
Folded       = "base03 base01"
IncSearch    = "base01 base09"
Italic       = ""
Macro        = "base08"
MatchParen   = "- base03"
ModeMsg      = "base0B"
MoreMsg      = "base0B"
Question     = "base0D"
Search       = "base01 base0A"
Substitute   = "base01 base0A"
SpecialKey   = "base03"
TooLong      = "base08"
Underlined   = "base08"
Visual       = "- base02"
VisualNOS    = "base08"
WarningMsg   = "base08"
WildMenu     = "base08 base0A"
Title        = "base0D"
Conceal      = "base0D base00"
Cursor       = "base00 base05"
NonText      = "base03"
LineNr       = "base03 base01"
SignColumn   = "base03 base01"
StatusLine   = "base04 base02"
StatusLineNC = "base03 base01"
VertSplit    = "base02 base02"
ColorColumn  = "- base01"
CursorColumn = "- base01"
CursorLine   = "- base01"
CursorLineNr = "base04 base01"
QuickFixLine = "- base01"
PMenu        = "base05 base01"
PMenuSel     = "base01 base05"
TabLine      = "base03 base01"
TabLineFill  = "base03 base01"
TabLineSel   = "base0B base01"

["Standard syntax highlighting"]
Boolean      = "base09"
Character    = "base08"
Comment      = "base09"
Conditional  = "base0E"
Constant     = "base09"
Define       = "base0E"
Delimiter    = "base0F"
Float        = "base09"
Function     = "base0D"
Identifier   = "base08"
Include      = "base0D"
Keyword      = "base0E"
Label        = "base0A"
Number       = "base09"
Operator     = "base05"
PreProc      = "base0A"
Repeat       = "base0A"
Special      = "base0C"
SpecialChar  = "base0F"
Statement    = "base08"
StorageClass = "base0A"
String       = "base0B"
Structure    = "base0E"
Tag          = "base0A"
Todo         = "base0A base01"
Type         = "base0A"
Typedef      = "base0A"

["C highlighting"]
cOperator  = "base0C"
cPreCondit = "base0E"

["C# highlighting"]
csClass                = "base0A"
csAttribute            = "base0A"
csModifier             = "base0E"
csType                 = "base08"
csUnspecifiedStatement = "base0D"
csContextualStatement  = "base0E"
csNewDecleration       = "base08"

["CSS highlighting"]
cssBraces    = "base05"
cssClassName = "base0E"
cssColor     = "base0C"

["Diff highlighting"]
DiffAdd     = "base0B base01"
DiffChange  = "base03 base01"
DiffDelete  = "base08 base01"
DiffText    = "base0D base01"
DiffAdded   = "base0B base00"
DiffFile    = "base08 base00"
DiffNewFile = "base0B base00"
DiffLine    = "base0D base00"
DiffRemoved = "base08 base00"

["Git highlighting"]
gitcommitOverflow      = "base08 -"
gitcommitSummary       = "base0B -"
gitcommitComment       = "base03 -"
gitcommitUntracked     = "base03 -"
gitcommitDiscarded     = "base03 -"
gitcommitSelected      = "base03 -"
gitcommitHeader        = "base0E -"
gitcommitSelectedType  = "base0D -"
gitcommitUnmergedType  = "base0D -"
gitcommitDiscardedType = "base0D -"
gitcommitBranch        = "base09 - b"
gitcommitUntrackedFile = "base0A -"
gitcommitUnmergedFile  = "base08 - b"
gitcommitDiscardedFile = "base08 - b"
gitcommitSelectedFile  = "base0B - b"

["GitGutter highlighting"]
GitGutterAdd          = "base0B base01"
GitGutterChange       = "base0D base01"
GitGutterDelete       = "base08 base01"
GitGutterChangeDelete = "base0E base01"

["HTML highlighting"]
htmlBold   = "base0A"
htmlItalic = "base0E"
htmlEndTag = "base05"
htmlTag    = "base05"

["JavaScript highlighting"]
javaScript       = "base05"
javaScriptBraces = "base05"
javaScriptNumber = "base09"

["pangloss/vim-javascript highlighting"]
jsOperator          = "base0D"
jsStatement         = "base0E"
jsReturn            = "base0E"
jsThis              = "base08"
jsClassDefinition   = "base0A"
jsFunction          = "base0E"
jsFuncName          = "base0D"
jsFuncCall          = "base0D"
jsClassFuncName     = "base0D"
jsClassMethodType   = "base0E"
jsRegexpString      = "base0C"
jsGlobalObjects     = "base0A"
jsGlobalNodeObjects = "base0A"
jsExceptions        = "base0A"
jsBuiltins          = "base0A"

["LSP highlighting"]
LspInfoBorder                    = "base05"
LspSignatureActiveParameter      = "base05 base03 b"
LspDiagnosticsDefaultError       = "base08"
LspDiagnosticsDefaultWarning     = "base09"
LspDiagnosticsDefaultHnformation = "base05"
LspDiagnosticsDefaultHint        = "base03"

["Mail highlighting"]
mailQuoted1 = "base0A"
mailQuoted2 = "base0B"
mailQuoted3 = "base0E"
mailQuoted4 = "base0C"
mailQuoted5 = "base0D"
mailQuoted6 = "base0A"
mailURL     = "base0D"
mailEmail   = "base0D"

["Markdown highlighting"]
markdownCode             = "base0B"
markdownError            = "base05 base00"
markdownCodeBlock        = "base0B"
markdownHeadingDelimiter = "base0D"

["NERDTree highlighting"]
NERDTreeDirSlash = "base0D"
NERDTreeExecFile = "base05"

["PHP highlighting"]
phpMemberSelector = "base05"
phpComparison     = "base05"
phpParent         = "base05"
phpMethodsVar     = "base0C"

["Python highlighting"]
pythonOperator  = "base0E"
pythonRepeat    = "base0E"
pythonInclude   = "base0E"
pythonStatement = "base0E"

["Ruby highlighting"]
rubyAttribute              = "base0D"
rubyConstant               = "base0A"
rubyInterpolationDelimiter = "base0F"
rubyRegexp                 = "base0C"
rubySymbol                 = "base0B"
rubyStringDelimiter        = "base0B"

["SASS highlighting"]
sassidChar    = "base08"
sassClassChar = "base09"
sassInclude   = "base0E"
sassMixing    = "base0E"
sassMixinName = "base0D"

["Signify highlighting"]
SignifySignAdd    = "base0B base01"
SignifySignChange = "base0D base01"
SignifySignDelete = "base08 base01"

["Spelling highlighting"]
SpellBad   = "- - u base08"
SpellLocal = "- - u base0C"
SpellCap   = "- - u base0D"
SpellRare  = "- - u base0E"

["Startify highlighting"]
StartifyBracket = "base03"
StartifyFile    = "base07"
StartifyFooter  = "base03"
StartifyHeader  = "base0B"
StartifyNumber  = "base09"
StartifyPath    = "base03"
StartifySection = "base0E"
StartifySelect  = "base0C"
StartifySlash   = "base03"
StartifySpecial = "base03"

["Java highlighting"]
javaOperator = "base0D"

["Treesitter highlighting"]
"@variable" = "link:Identifier"

["Neogit highlighting"]
NeogitDiffDeleteHighlight = "link:DiffDelete"
NeogitDiffDeleteCursor    = "link:DiffDelete"
NeogitDiffDeletions       = "link:DiffDelete"
NeogitDiffDeletion        = "link:DiffDelete"
NeogitDiffDelete          = "link:DiffDelete"
NeogitChangeDeleted       = "link:DiffDelete"
